name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          # - macOS-latest
    env:
      NIM_VERSION: 1.0.4
    steps:
      - uses: actions/checkout@v2
      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v1
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}
      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v1
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ env.NIM_VERSION }}
      - run: nimble build -d:release -Y
      - run: nimble test -Y
      - run: nimble install -Y
      - run: misskey-xp-bot
      - run: nimble doc --project --index:on -o:docs src/misskey-xp-bot.nim

      - name: Create artifact
        if: runner.os == 'Linux'
        run: tar czf misskey-xp-bot_${{ runner.os }}.tar.gz README.md misskey-xp-bot

      - name: Create artifact - Win
        if: runner.os == 'Windows'
        run: tar czf misskey-xp-bot_${{ runner.os }}.tar.gz README.md misskey-xp-bot.exe

      - name: Release binary
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: misskey-xp-bot*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
